# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GOT' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.6.0'
  pod 'SwiftyJSON', '~> 4.0.0'
  pod 'SVProgressHUD', '~> 2.2.5'
  # Pods for GOT

  target 'GOTTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
